// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQYO_v6VGmN2cfOhYb54bH6bJ3OVX2Rs',
    appId: '1:401377511416:web:63d7e25bbaf0beb5bd380d',
    messagingSenderId: '401377511416',
    projectId: 'loja-flutter-fokelvin',
    authDomain: 'loja-flutter-fokelvin.firebaseapp.com',
    storageBucket: 'loja-flutter-fokelvin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcGVMqq9i3OpZ_cbDlhP71iMftAJZgrHY',
    appId: '1:401377511416:android:f45e4fc6bf37618bbd380d',
    messagingSenderId: '401377511416',
    projectId: 'loja-flutter-fokelvin',
    storageBucket: 'loja-flutter-fokelvin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtj8n28eedtWEYs8Ry66FVWmViXmyoG34',
    appId: '1:401377511416:ios:5a9524c960d8f65ebd380d',
    messagingSenderId: '401377511416',
    projectId: 'loja-flutter-fokelvin',
    storageBucket: 'loja-flutter-fokelvin.firebasestorage.app',
    iosBundleId: 'com.example.lojaVirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtj8n28eedtWEYs8Ry66FVWmViXmyoG34',
    appId: '1:401377511416:ios:5a9524c960d8f65ebd380d',
    messagingSenderId: '401377511416',
    projectId: 'loja-flutter-fokelvin',
    storageBucket: 'loja-flutter-fokelvin.firebasestorage.app',
    iosBundleId: 'com.example.lojaVirtual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSQYO_v6VGmN2cfOhYb54bH6bJ3OVX2Rs',
    appId: '1:401377511416:web:4ad2d038a48e9451bd380d',
    messagingSenderId: '401377511416',
    projectId: 'loja-flutter-fokelvin',
    authDomain: 'loja-flutter-fokelvin.firebaseapp.com',
    storageBucket: 'loja-flutter-fokelvin.firebasestorage.app',
  );
}
